// utils/eventUtils.js

// サンプルイベントデータ
export const sampleEvents = [
  {
      id: 1,
      title: "明治維新",
      startDate: new Date(1868, 0, 3),
      endDate: new Date(1868, 0, 3),
      description:
        "#江戸幕府 が終焉し、#明治政府 が成立。日本の近代化が始まる重要な転換点となった。",
      tags: ["明治維新", "江戸幕府", "明治政府", "日本史", "歴史"],
      position: { x: 0, y: 60 },
    },
    {
      id: 2,
      title: "終戦",
      startDate: new Date(1945, 7, 15),
      endDate: new Date(1945, 7, 15),
      description: "太平洋戦争が終結。日本が連合国に降伏した。",
      tags: ["終戦", "太平洋戦争", "日本史", "歴史"],
      position: { x: 0, y: 60 },
    },
    {
      id: 101,
      title: "バウハウス設立",
      startDate: new Date(1919, 3, 1),
      endDate: new Date(1919, 3, 1),
      description:
        "#モダニズム の原点。#バウハウス は機能美と合理性を追求した芸術学校。",
      tags: ["バウハウス", "モダニズム", "建築教育", "近代建築"],
      position: { x: 0, y: 80 },
    },
    {
      id: 102,
      title: "サヴォア邸",
      startDate: new Date(1931, 0, 1),
      endDate: new Date(1931, 0, 1),
      description: "近代建築の五原則を体現した #ル・コルビュジエ の代表作。",
      tags: ["ル・コルビュジエ", "近代建築", "モダニズム", "住宅建築"],
      position: { x: 0, y: 80 },
    },
    {
      id: 103,
      title: "落水荘",
      startDate: new Date(1939, 0, 1),
      endDate: new Date(1939, 0, 1),
      description: "自然との調和を実現した #有機的建築 の傑作。",
      tags: ["フランク・ロイド・ライト", "有機的建築", "アメリカ建築"],
      position: { x: 0, y: 90 },
    },
    {
      id: 104,
      title: "CIAM設立",
      startDate: new Date(1928, 0, 1),
      endDate: new Date(1928, 0, 1),
      description: "#CIAM は近代建築の国際的普及を目指す会議体。",
      tags: ["CIAM", "都市計画", "近代建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 105,
      title: "広島平和記念資料館",
      startDate: new Date(1955, 0, 1),
      endDate: new Date(1955, 0, 1),
      description: "#丹下健三 による戦後日本のモダニズム建築。",
      tags: ["丹下健三", "日本建築", "広島", "モダニズム"],
      position: { x: 0, y: 100 },
    },
    {
      id: 106,
      title: "TWAフライトセンター",
      startDate: new Date(1962, 0, 1),
      endDate: new Date(1962, 0, 1),
      description: "曲線的なフォルムが象徴的な #未来派建築 の代表作。",
      tags: ["サーリネン", "空港建築", "未来派建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 107,
      title: "メタボリズム",
      startDate: new Date(1960, 0, 1),
      endDate: new Date(1960, 0, 1),
      description: "新陳代謝する都市を構想した #メタボリズム 運動。",
      tags: ["メタボリズム", "都市構想", "日本建築"],
      position: { x: 0, y: 110 },
    },
    {
      id: 108,
      title: "大分県立図書館",
      startDate: new Date(1966, 0, 1),
      endDate: new Date(1966, 0, 1),
      description:
        "#磯崎新 初期の代表作。#モダニズム に根ざしつつ独自の構造美を持つ。",
      tags: ["磯崎新", "図書館建築", "日本建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 109,
      title: "ロイドビル",
      startDate: new Date(1986, 0, 1),
      endDate: new Date(1986, 0, 1),
      description: "#ハイテック建築 の象徴的作品。",
      tags: ["ハイテック建築", "リチャード・ロジャース", "イギリス建築"],
      position: { x: 0, y: 90 },
    },
    {
      id: 110,
      title: "ザハ・ハディド注目を浴びる",
      startDate: new Date(1983, 0, 1),
      endDate: new Date(1983, 0, 1),
      description: "1983年の #香港のピーク・クラブ 計画で国際的注目を浴びた。",
      tags: ["ザハ・ハディド", "女性建築家", "ポストモダン"],
      position: { x: 0, y: 90 },
    },
    {
      id: 111,
      title: "せんだいメディアテーク",
      startDate: new Date(2001, 0, 1),
      endDate: new Date(2001, 0, 1),
      description: "#日本建築 における情報化時代の先駆。",
      tags: ["伊東豊雄", "情報建築", "せんだいメディアテーク"],
      position: { x: 0, y: 100 },
    },
    {
      id: 112,
      title: "テルメ・ヴァルス",
      startDate: new Date(1996, 0, 1),
      endDate: new Date(1996, 0, 1),
      description: "素材と空間体験を重視した #ミニマリズム 建築の傑作。",
      tags: ["ピーター・ズントー", "スイス建築", "ミニマリズム"],
      position: { x: 0, y: 90 },
    },
    {
      id: 113,
      title: "ボルドーの家",
      startDate: new Date(1998, 0, 1),
      endDate: new Date(1998, 0, 1),
      description: "#OMA による可変性のある住宅。",
      tags: ["レム・コールハース", "OMA", "住宅建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 114,
      title: "東京国立博物館法隆寺宝物館",
      startDate: new Date(1999, 0, 1),
      endDate: new Date(1999, 0, 1),
      description: "静謐で洗練された日本の #現代建築 。",
      tags: ["谷口吉生", "ミュージアム建築", "日本建築"],
      position: { x: 0, y: 95 },
    },
    {
      id: 115,
      title: "光の教会",
      startDate: new Date(1989, 0, 1),
      endDate: new Date(1989, 0, 1),
      description: "#安藤忠雄 による光と空間の宗教建築。",
      tags: ["安藤忠雄", "光の教会", "宗教建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 116,
      title: "梅田スカイビル",
      startDate: new Date(1993, 0, 1),
      endDate: new Date(1993, 0, 1),
      description: "都市を空中でつなぐ構想を体現した #空中都市 建築。",
      tags: ["原広司", "空中都市", "日本建築"],
      position: { x: 0, y: 90 },
    },
    {
      id: 117,
      title: "中銀カプセルタワー",
      startDate: new Date(1972, 0, 1),
      endDate: new Date(1972, 0, 1),
      description: "#メタボリズム を象徴するカプセル型集合住宅。",
      tags: ["黒川紀章", "中銀カプセルタワー", "集合住宅"],
      position: { x: 0, y: 110 },
    },
    {
      id: 118,
      title: "私の家",
      startDate: new Date(1954, 0, 1),
      endDate: new Date(1954, 0, 1),
      description: "#戦後建築 の代表的な小住宅。",
      tags: ["清家清", "住宅建築", "戦後建築"],
      position: { x: 0, y: 100 },
    },
    {
      id: 119,
      title: "ヴィトラ・デザイン・ミュージアム",
      startDate: new Date(1989, 0, 1),
      endDate: new Date(1989, 0, 1),
      description: "ポストモダンの象徴的なデザインミュージアム。",
      tags: ["フランク・ゲーリー", "ポストモダン", "美術館"],
      position: { x: 0, y: 90 },
    },
    {
      id: 120,
      title: "シアトル図書館",
      startDate: new Date(2004, 0, 1),
      endDate: new Date(2004, 0, 1),
      description: "#レム・コールハース による #情報空間 の実験。",
      tags: ["OMA", "シアトル図書館", "情報空間"],
      position: { x: 0, y: 100 },
    }
];

// 初期タグ
export const initialTags = [
  "明治維新", "江戸幕府", "明治政府", "終戦", "太平洋戦争",
  "日本史", "歴史", "政治", "文化", "モダニズム", "近代建築"
];